version: "3.5"

services:
  postgres:
    container_name: meet-my-job
    image: postgres:latest
    environment:
      POSTGRES_USER: meetmyjobuser
      POSTGRES_PASSWORD: meetmyjobpassword
      POSTGRES_DB: meetmyjobdatabase
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: meetmyjobuser
      MINIO_ROOT_PASSWORD: meetmyjobpassword
    command: server /data --console-address ":9001"

volumes:
  postgres-db:
    driver: local
